name: feed_estimator
description: A new Flutter project.

publish_to: 'none'

version: 0.1.1+10

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  devicelocale: ^0.8.2
  equatable: ^2.0.7
  flex_color_scheme: ^8.4.0
  flutter_riverpod: ^3.0.3
  flutter_spinkit: ^5.2.2
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  in_app_review: ^2.0.11
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  printing: ^5.13.2
  quickalert: ^1.1.0
  riverpod_annotation: ^3.0.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0
  sqflite_common_ffi_web: ^1.1.0
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  go_router_builder: ^4.1.3
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/raw/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf