name: feed_estimator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.1.1+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.15
  go_router: ^9.0.0
  sqflite:
  flutter_riverpod: ^2.3.6
  #flutter_spinkit:
  #flutter_sparkline: ^0.1.0
  freezed_annotation: ^2.2.0
  flex_color_scheme: ^7.1.2
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  path: ^1.8.3
  go_router_builder: ^2.1.1
  intl: ^0.18.1
  pdf:
  printing:
  devicelocale:
  quickalert:
  package_info_plus:
  in_app_review: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints:
  riverpod_generator:
  build_runner:
  freezed:
  json_serializable:
  riverpod_lint:
  custom_lint:


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/raw/
    - assets/images/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
